se is nu ru et tgc sc hls cin cino+=j1 sw=2 sts=2 bs=2 mouse=a "encoding=utf-8 ls=2
syn on | colo desert | filetype indent on
inoremap {<CR> {<CR>}<ESC>O
map \c <ESC>:w<CR>:!g++ "%" -o "%<" -std=c++17 -Dtoo_soft -Wall -Wextra -Wshadow -Wfatal-errors -Wconversion -fsanitize=address,undefined -g && echo success<CR>
map \f <ESC>:w<CR>:!g++ "%" -o "%<" -O2 -std=c++17 && echo success<CR>
map \e <ESC>:!./"%<"<CR>
ca Hash w !cpp -dD -P -fpreprocessed \| tr -d '[:space:]' \| md5sum \| cut -c-6
" setxkbmap -option caps:ctrl_modifier
